services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: product_user
      MYSQL_PASSWORD: product_user_password
      MYSQL_DATABASE: Sekretariat
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [
        "CMD-SHELL",
        "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"
      ]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 50s

  spring-boot-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Sekretariat
      SPRING_DATASOURCE_USERNAME: product_user
      SPRING_DATASOURCE_PASSWORD: product_user_password

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: [ "npm", "start" ]

volumes:
  mysql-data: